# Generated by Django 5.1.7 on 2025-04-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_product_when',
        ),
    ]
